### ISSUE TITLE
Legg inn et bilde dere ønsker å bruke til kontaktkort.

### ISSUE THREAD

**Issue by ineant** [mathiasirgemo/How-We-Roll-6A#10]

**Comment by jaimemontanares** [comment]
![Image](https://user-images.githubusercontent.com/112397585/200656267-ba5f7f11-4853-4edd-814c-e8caa17351f3.png)

Jaime - bilde. 
Bare si i fra om du trenger en cropped versjon.

**Comment by Tj12501** [comment]
![image](https://user-images.githubusercontent.com/112393967/200879344-1ee15ed2-d491-4779-941a-6e35b7892223.png)

**Comment by LukaszDK98** [comment]
![vp6xrp8mo2i41](https://user-images.githubusercontent.com/111511076/200940329-a0b32f52-ab9c-4eaf-980a-ffac2c50be8c.jpg)

**Comment by JosefBurkan** [comment]
![Image](https://user-images.githubusercontent.com/112654299/200940413-dace7d9e-eb2e-4d96-95be-dba8f197dbbe.jpeg)

tlf: 97472745

**Comment by erny03** [comment]
![kontaktkortselfie](https://user-images.githubusercontent.com/112587945/200942494-48c155cf-fbcb-4569-a03b-cd6cf77826cd.jpg)
tok bare bilde med telefonen kjapt så vet ikke om det blir for uklart eller problemer pga. resolution på bilde. bare så ifra isåfall
