### ISSUE TITLE
skriv inn telefon nr. og epostadresse som dere ønsker å bli kontaktet på

### ISSUE THREAD

**Issue by ineant** [mathiasirgemo/How-We-Roll-6A#11]

**Comment by mathiasirgemo** [comment]
Mathias Irgemo
+4797508577
mathasir@uia.no

**Comment by jaimemontanares** [comment]
Jaime Montanares
+47 41 32 86 16
jsmont05@uia.no

**Comment by Tj12501** [comment]
Thomas John Hines Frivold
+47 97 86 88 77
tjfrivold@uia.no

**Comment by erny03** [comment]
Erik Nygård
+47 901 74 903
erikn@uia.no

**Comment by LukaszDK98** [comment]
Lukasz Kucharczyk 
+47 465 963 87
lukaszdk@uia.no

**Comment by mathiasirgemo** [comment]
ferdig
