### ISSUE TITLE
#1 Forside

### ISSUE THREAD

**Issue by mathiasirgemo** [mathiasirgemo/How-We-Roll-6A#3]
Skal inneholde følgende

- Link til egen Kontaktkort Html Side
- Link til egen Web-Form Html side
- Link til egen Web-Rapport Html Side
- Link til Gruppe Kalender
- Link til Gruppe Møtereferat

**Comment by jaimemontanares** [comment]
https://www.figma.com/file/LTzB5P8C1u8UeU0vPUHDI7/Forside?node-id=0%3A1&t=GjUwME9FTl5IpYQq-1

**Comment by jaimemontanares** [comment]
**Forslag til forside tekst:** 
"Velkommen til How We Roll for gruppe 6A! Dette verktøyet er til for å registrere gruppe medlemmer og lage profiler ved bruk av slider verktøy samt en kort beskrivende tekst."

**Comment by mathiasirgemo** [comment]
Hva trenger du hjelp til, Jaime? 👍

**Comment by jaimemontanares** [comment]
Jeg har gjerne lyst til å få mitt grid til å bli "responsive". Bilde forsvinner til sida når ui blir trangere akkurat nå.

**Comment by jaimemontanares** [comment]
Den er ikke perfekt. Jeg kunne ha planlagt antall kolonner bedre. Men siden oppleves mye mer "responsive" enn i starten.

**Comment by jaimemontanares** [comment]
Så på en youtube video der en mobil versjon kan absolutt lages ut av de vi har. Rekker ikke innen frist i kveld.

**Comment by mathiasirgemo** [comment]
@jaimemontanares Okei, har du forsøkt med flex-grid?

Flex er responsive og vil flyttes ut i fra hvor stor siden er.
Setter du Display: Flex; på hele siden vil den være responsive


Du kan i tillegg sette deg egne styles når skjermen er liten eller stor, da bruker du @media{ 800px} <- eks

**Comment by jaimemontanares** [comment]
Jeg har sett på noen slike muligheter, men jeg vil sette meg ned med egen fork hvis jeg skal eksperimentere videre. Takk for tips.
