### ISSUE TITLE
Legge inn informasjon om seg selv i webform

### ISSUE THREAD

**Issue by mathiasirgemo** [mathiasirgemo/How-We-Roll-6A#30]
Legg inn informasjon om deg selv og legg inn trxid og dato i kommentarfeltet

**Comment by jaimemontanares** [comment]
{
  "navn": "Jaime",
  "Telefonnummer": "41328616",
  "Epost": "jsmont05@uia.no",
  "MorgenfuglEllerNatteravn": "87",
  "GruppeEllerAlene": "67",
  "Forklaring": "25",
  "Arbeidstid": "25",
  "Introvert/Ekstrovert": "11",
  "trxid": "a6e8b4002a809d7c0aeb60e8e6773a9a",
  "time": "20221210221043"
}
