### ISSUE TITLE
Oppsett av sider

### ISSUE THREAD

**Issue by mathiasirgemo** [mathiasirgemo/How-We-Roll-6A#9]
Når alle skal lage sin del er det viktig at det brukes samme oppsett.

Vi bruker ekstern CSS fil (link som henviser til en css fil i head)

All javascript kode skal føres inn i samme html dokument

**Comment by ineant** [comment]
[FORSLAG TIL FARGE KOMBINASJON.pdf](https://github.com/mathiasirgemo/How-We-Roll-6A/files/9951071/FORSLAG.TIL.FARGE.KOMBINASJON.pdf)

**Comment by ineant** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/font-family
likte litt "gill sans" til font

**Comment by mathiasirgemo** [comment]
Har lagt inn navbar og Banner standard i main :)
